window.PROJECT_DATA = {
  snapshot: {
    status: "训练中",
    checkpoint: 40,
    lastCuratedStep: 45,
    targetStep: 100,
    description: "从 Step 40 checkpoint 恢复，重新计算 Step 41–45；实时进度以 W&B 为准。",
  },
  experiments: [
    {
      stage: "Base",
      model: "Qwen3-4B",
      protocol: "40 tasks × 4",
      result: "39.375%",
      note: "普通版基线",
      status: "baseline",
    },
    {
      stage: "SFT",
      model: "Qwen3-4B + LoRA step96",
      protocol: "40 tasks × 4",
      result: "69.375%",
      note: "111 / 160",
      status: "complete",
    },
    {
      stage: "Signal test",
      model: "SFT step96",
      protocol: "16 tasks × 8",
      result: "76.38%",
      note: "97 / 127 valid",
      status: "complete",
    },
    {
      stage: "Vanilla GRPO",
      model: "SFT merged + RL LoRA",
      protocol: "100 steps · 4×8",
      result: "训练中",
      note: "final eval pending",
      status: "active",
    },
  ],
  passk: [
    { label: "Pass¹", value: 69.375 },
    { label: "Pass²", value: 55.417 },
    { label: "Pass³", value: 47.5 },
    { label: "Pass⁴", value: 42.5 },
  ],
  stepFlow: [
    { title: "任务采样", owner: "VERL DataLoader", shape: "4 task records", detail: "从 64 个训练任务中无放回抽取 4 个任务。16 step 构成一轮完整任务覆盖。", why: "控制数据边界，并让每个训练任务在单个 epoch 中只出现一次。" },
    { title: "组扩展", owner: "Rollout scheduler", shape: "4 × 8 = 32 requests", detail: "每个任务复制为 8 条随机 rollout，形成 GRPO 的四个独立比较组。", why: "组内成功与失败的差异就是相对优势信号。" },
    { title: "环境初始化", owner: "RetailSession", shape: "32 isolated states", detail: "每条轨迹创建独立用户状态、数据库副本与任务 verifier，调用 session.start() 得到首条用户消息。", why: "并发轨迹不能互相污染订单、用户或支付状态。" },
    { title: "Prompt 编码", owner: "Chat Template + tokenizer", shape: "prompt_ids ≤ 6,144", detail: "结构化消息先经过固定 no-think Chat Template，再被 tokenizer 转换为 token IDs。", why: "保证 SFT 和在线 rollout 遵循同一个工具调用 token 协议。" },
    { title: "Assistant 生成", owner: "vLLM", shape: "up to 32 active sequences", detail: "vLLM 使用 KV Cache、chunked prefill 与 prefix caching 异步生成下一轮 Assistant token。", why: "不同轨迹等待 User API 时，GPU 仍可以推进其他序列。" },
    { title: "动作路由", owner: "AgentLoop", shape: "tool call | user message", detail: "解析 Assistant 消息；工具调用交给环境，普通回复交给用户模拟器。返回 observation 追加到同一 token 历史。", why: "while 循环是整条轨迹的最小控制单元。" },
    { title: "轨迹终止", owner: "RetailSession", shape: "≤ 12,288 response tokens", detail: "User STOP、最大步数、协议错误、上下文上限或基础设施失败都可能结束轨迹，并保留明确终止原因。", why: "模型失败和基础设施错误必须分开统计。" },
    { title: "二元奖励", owner: "τ² verifier", shape: "reward ∈ {0, 1}", detail: "根据最终环境状态和任务要求计算官方二元奖励；基础设施失败不进入模型 reward。", why: "先建立严格可比的 Vanilla 基线。" },
    { title: "Batch 张量化", owner: "VERL", shape: "input / mask / position / reward", detail: "32 条变长轨迹组成训练 batch；attention mask 描述真实 token，response mask 只标记 Assistant 生成 token。", why: "上下文参与因果建模，但只有策略动作参与 policy loss。" },
    { title: "组内 Advantage", owner: "GRPO", shape: "32 scalar advantages", detail: "每组 8 个 reward 做标准化，得到轨迹级 advantage，再广播到该轨迹的所有 Assistant token。", why: "不训练额外 Critic，也能表达同任务下行为的相对好坏。" },
    { title: "Reference Forward", owner: "Frozen SFT policy", shape: "ref_log_prob per assistant token", detail: "冻结的 SFT merged model 计算参考 log-prob，用于 KL 正则。", why: "限制 RL policy 过快偏离已经具备工具能力的 SFT 起点。" },
    { title: "Actor Forward", owner: "FSDP Actor", shape: "new_log_prob per assistant token", detail: "移除 padding 后按真实 token 动态装箱；Transformer 处理完整上下文，LM Head 只投影 Assistant token。", why: "在保持条件概率正确的前提下，删除最昂贵的无用计算。" },
    { title: "Loss 与 Backward", owner: "Autograd", shape: "scalar loss → gradients", detail: "由 probability ratio、advantage、clip 与 KL 构成标量 loss；backward 为 RL LoRA 累积梯度。", why: "loss 的数值只是入口，真正更新方向来自它对每个参数的导数。" },
    { title: "更新与同步", owner: "Optimizer + vLLM", shape: "new RL LoRA + checkpoint", detail: "optimizer 更新 RL LoRA，随后将新权重同步到 vLLM；按频率保存 LoRA、optimizer、extra 与 DataLoader 状态。", why: "下一个 step 必须由刚更新后的 policy 重新采样。" },
  ],
};
